= MFL (MAT File Library)

== 0.5.2 (SNAPSHOT)

* Improved streaming source fallback for files that are larger than 2GB and can't be memory mapped. The `FileInputStream` wrapper was changed to using buffered IO via `FileChannel / ByteBuffer`.

== 0.5.1
* Removed resources (changelog, license, etc.) from generated jar to avoid issues with e.g. ProGuard trying to copy them into the uber jar
* Fixed an issue when reading empty sparse matrices from `R2018b` due to an undocumented format change
* Fixed writing empty `MatrixSparseCSC` EJML types

== 0.5
* Renamed maven coordinates and Jigsaw module names

= Mat-File IO (previous name)

== 0.4.1
* Added parser support for `v3` MCOS subsystems. (Note: The `v2` parser seems to handle `v3` just fine, but we don't actually know where the differences are). Thanks `@nedtwigg`

== 0.4
This change breaks backwards compatibility with `0.3` for some corner case use cases.

* Removed `Array::isGlobal()`
* Moved `NamedArray` to `MatFile.Entry`
* Added `MatFile.Entry::isGlobal()`
* Added `MatFile::addEntry(entry)`
* Added `Mat5Writer::writeEntry(entry)`
* Renamed `Mat5Reader::setArrayFilter(ArrayFilter)` to `Mat5Reader::setEntryFilter(EntryFilter)`
* Added extension module for converting `EJML` matrices
* Added `Sinks::newStreamingFile(file, append)` to add entries to existing MAT files

== 0.3
* Added `hashCode()` and `equals()` to all Arrays. Thanks `@nedtwigg`
* Fixed a bug that caused the `global` flag to be ignored during construction. Thanks `@nedtwigg`
* Fixed a bug that caused field names inside structs and objects to be serialized incorrectly

== 0.2
* Moved `common.util` to `mat.util`
* Removed unused utilities
* Removed multi-release jar dependency due to lack of support for some build tools (e.g. obfuscation)
* Improved streaming file sink implementation
* Changed `StreamingDoubleMatrix2D` to be a test example
* `MatFile` API
** Renamed `size()` to `getNumEntries()`
** Added `clear()`
** Added `getEntries()` for accessing `Iterable<NamedArray>`

== 0.1.2
* fixed binary incompatibilities with Java 6 that were introduced by compiling with JDK 9

== 0.1.1
* added license headers to all files

== 0.1
* initial release