= MFL (MAT File Library)

// == 0.6.0-SNAPSHOT

== 0.5.11

* added support for mcos version 4 introduced in R2022b (thanks @nedtwigg)

== 0.5.10

* added custom allocator support to char arrays (fixes #69)

== 0.5.9

* Improved error message for v7.3 files

== 0.5.8

* Fixed an overflow issue when reading variables that are >1GB compressed (fixes #65).
* Changed rules to allow reading of 2-4 GB variables (fixes #64). Note that MATLAB has a 2 GB write limit, but it can read 4 GB variables saved by Octave.

== 0.5.7
* Removed the special subsystem entry from the content list to avoid confusing users
* Changed EJML Scope to `provided`
* Fixed a bug where EJML's `CMatrixRmaj` was stored as `ZMatrixRmaj`
* Added functionality to automatically determine EJML matrix based on data type

== 0.5.6
* Fixed default endian-ness for writing to memory mapped files (fixes #58)
* Fixed a bug that caused disk access to fail on Android (fixes #56)
* Disabled unsafe access for ARM platforms to avoid potential unaligned access issues

== 0.5.5
* Fixed bug that caused the struct index map to be wrong after field removal (fixes #53, thanks @ryanlb1000)
* Added size checks to prevent variables >2GB from being serialized. (fixes #55, thanks @syr)
* Removed Java8 hash methods. (fixes #51)

== 0.5.4
* Improved string display for function handles and Java objects
* Fixed a subsys-related bug that caused issues when reading mat files in Octave. Thanks @grabarczyk-t

== 0.5.3
* Fixed a bug that caused some sparse matrices to fail (nzMax > numNz). Thanks @mephenor
* Added `getNumNonZero()` to sparse interface and deprecated `getNzMax()`. This is equivalent to MATLAB's `nnz`.

== 0.5.2

* Improved streaming source fallback for files that are larger than 2GB and can't be memory mapped. The `FileInputStream` wrapper was changed to using buffered IO via `FileChannel / ByteBuffer`.
* Removed hyphens from Jigsaw module name. Thanks @stffnjng
* Added convenience methods to `Mat5` for reading from and writing to disk

== 0.5.1
* Removed resources (changelog, license, etc.) from generated jar to avoid issues with e.g. ProGuard trying to copy them into the uber jar
* Fixed an issue when reading empty sparse matrices from `R2018b` due to an undocumented format change
* Fixed writing empty `MatrixSparseCSC` EJML types

== 0.5
* Renamed maven coordinates and Jigsaw module names

= Mat-File IO (previous name)

== 0.4.1
* Added parser support for `v3` MCOS subsystems. (Note: The `v2` parser seems to handle `v3` just fine, but we don't actually know where the differences are). Thanks `@nedtwigg`

== 0.4
This change breaks backwards compatibility with `0.3` for some corner case use cases.

* Removed `Array::isGlobal()`
* Moved `NamedArray` to `MatFile.Entry`
* Added `MatFile.Entry::isGlobal()`
* Added `MatFile::addEntry(entry)`
* Added `Mat5Writer::writeEntry(entry)`
* Renamed `Mat5Reader::setArrayFilter(ArrayFilter)` to `Mat5Reader::setEntryFilter(EntryFilter)`
* Added extension module for converting `EJML` matrices
* Added `Sinks::newStreamingFile(file, append)` to add entries to existing MAT files

== 0.3
* Added `hashCode()` and `equals()` to all Arrays. Thanks `@nedtwigg`
* Fixed a bug that caused the `global` flag to be ignored during construction. Thanks `@nedtwigg`
* Fixed a bug that caused field names inside structs and objects to be serialized incorrectly

== 0.2
* Moved `common.util` to `mat.util`
* Removed unused utilities
* Removed multi-release jar dependency due to lack of support for some build tools (e.g. obfuscation)
* Improved streaming file sink implementation
* Changed `StreamingDoubleMatrix2D` to be a test example
* `MatFile` API
** Renamed `size()` to `getNumEntries()`
** Added `clear()`
** Added `getEntries()` for accessing `Iterable<NamedArray>`

== 0.1.2
* fixed binary incompatibilities with Java 6 that were introduced by compiling with JDK 9

== 0.1.1
* added license headers to all files

== 0.1
* initial release