= MatlabTools

This `MatlabTools` repo is intended to be an open source collection of some of our MATLAB related Java libraries. This is an ongoing effort, so we will be adding more as we go.

== MatlabTools :: IO

`MatlabTools::IO` is a Java library for reading and writing MAT Files that are compatible with MATLAB's MAT-File Format.

It's overall design goals are; 1) to support working with large amounts of data on heap constrained and allocation limited environments, 2) to allow users to serialize custom data classes without having to convert to temporary objects, 3) to provide a user-friendly API that adheres to MATLAB's semantic behavior.

This library is free, written in 100% Java, and has been released under an Apache v2.0 license. It works with Java 6 and higher, including Java 9 and 10.

For more information and usage examples, please refer to the link:./io[documentation].

== Building Sources

The created sources include Java 9's `module-info.java`, but are otherwise backwards compatible with Java 6. The contained unit tests may use Java 8 syntax, so the project needs to be compiled with at least JDK 8.

Building with JDK 9 and above

    mvn package

Building with JDK 8

    mvn package -PnoJava9

For more information, please check the CI build-script link:Jenkinsfile[]