= MatlabTools

This `MatlabTools` repo is intended to be an open source collection of some of our MATLAB related Java libraries. This is an ongoing effort, so we will be adding more as we go.

== MatlabTools :: IO

`MatlabTools::IO` is a Java library for reading and writing MATLAB's https://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf[Level 5 MAT-File format], which has been the default for `.mat` and `.fig` files since https://en.wikipedia.org/wiki/MATLAB#Release_history[MATLAB 5.0 (R8)] in 1996. The Level 5 format includes `save` flags `-v6` and `-v7`, but not `-v4` or `-v7.3`. See MAT-File https://de.mathworks.com/help/matlab/import_export/mat-file-versions.html[Versions] for more info.

The overall design goals are; 1) to be as memory efficient as possible to support working with large amounts of data on heap constrained and allocation limited environments, 2) to allow users to serialize custom data classes without having to convert to temporary objects, 3) to provide a user-friendly API that follows MATLAB's semantic behavior and reduces casts and boiler plate code wherever possible.

This library is free, written in 100% Java, and has been released under an Apache v2.0 license. It works with Java 6 and higher, including Java 9 and 10.

For more information and usage examples, please refer to the sub-readme at link:./io[MatlabTools::IO].

== Building Sources

The created sources include Java 9's `module-info.java`, but are otherwise backwards compatible with Java 6. The contained unit tests may use Java 8 syntax, so the project needs to be compiled with at least JDK 8.

Building with JDK 9 and above

    mvn package

Building with JDK 8

    mvn package -PnoJava9

For more information, please check the CI build-script link:Jenkinsfile[]